apiVersion: v1
kind: ConfigMap
metadata:
  name: scraper-config
  namespace: deal-aggregator
  labels:
    app: scraper
data:
  # Same hostname as MongoDB Service name
  MONGO_URI: "mongodb://mongodb:27017/deal-aggregator"
  RETRY_DELAY_MS: "3000"
